#!/bin/bash
# Rebuilds internal/password/common-passwords.txt from SecLists' 1,000,000 most
# common passwords (MIT licensed): the 3,000 most common of at least 15
# characters, in rank order. Shorter ones are already refused by the length
# rule, and 3,000 is what OWASP ASVS asks for.
set -euo pipefail

source_url="https://raw.githubusercontent.com/danielmiessler/SecLists/master/Passwords/Common-Credentials/xato-net-10-million-passwords-1000000.txt"
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
target="$repo_root/internal/password/common-passwords.txt"

download_dir="$(mktemp -d)"
trap 'rm -rf "$download_dir"' EXIT
curl -fsSL "$source_url" -o "$download_dir/top-1000000.txt"

{
	echo "# The 3,000 most common passwords of at least 15 characters, most common"
	echo "# first, one per line, compared without case. Shorter passwords are"
	echo "# already refused by length."
	echo "# Generated by scripts/update-common-passwords.sh from SecLists (MIT):"
	echo "# $source_url"
	python3 -I -c '
import sys
seen = set()
for raw in open(sys.argv[1], encoding="utf-8", errors="ignore"):
    password = raw.rstrip("\r\n")
    key = password.lower()
    if len(password) >= 15 and not password.startswith("#") and key not in seen:
        seen.add(key)
        print(password)
        if len(seen) == 3000:
            break
' "$download_dir/top-1000000.txt"
} > "$target"

echo "Wrote $(grep -vc '^#' "$target") passwords to $target"
